### `4-4.KNN(K-Nearest Neighbor)`

* 가장 가까운 K개의 이웃의 대표 속성값을 통해 데이터를 예측하는 알고리즘

* KNN의 장점
    * 간단한 구조
    * 이해가 쉬움
    * 구현이 쉬움
    * 강력한 결과 (노력 대비 좋은 성능)
    * 데이터 수가 적어도 Model을 생성할 수 있음

* KNN의 특징
    * 가장 많은 자료 수가 존재하는 클래스/속성을 예측값으로 설정
    * 여러 개의 K값으로 테스트를 해본 후 가장 좋은 방법으로 나눔
        * K값에 따라서 분류 결과가 달라지고 정확도와 신뢰도까지 영향을 받음
    * 모든 계산이 이뤄진 후에 분류를 수행하므로 사례 기반 학습 또는 메모리 기반 학습으로 부름
    * 훈련 데이터에 Target이 존재하는 지도 학습 알고리즘
    * 각 속성에 맞춰 레벨을 분류하는 방식으로 예측 진행
    * KNN의 적용 분야
        * 분류에 해당하는 대부분의 업무 분야에 적용 가능
        * 얼굴 인식이나 글자 인식 등 이미지 인식
        * 적절한 상품 추천
        <br/>등

* KNN의 적용법
    1. 예측 대상을 기점으로 K개의 이웃이 포함된 대표 집단을 만듦
    2. 대표 집단 내에서 클래스 또는 속성을 설정하고 집단 내에서 우세한 레벨을 찾음
    3. 예측 대상이 우세한 레벨과 동일한 레벨이라고 가정하여 예측 진행
        1) 단순 KNN은 집단 내의 거리가 무시될 수 있음
        2) 거리를 고려한 weighted KNN을 사용하기도 함
        <br/> "거리의 역수"나 "거리의 역수의 제곱의 역수"를 가중치로 두어 정확도가 높아짐
    

* 용도에 따라 다음과 같은 python 함수를 사용
    * KNeighborsClassifier(): 분류 알고리즘
    * KNeighborsRegressor(): 연속 데이터 예측 알고리즘

---
#### 코드블럭1
**KNN 예시 코드 1 시작**

이상형 데이터에 대한 KNN Model

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# "ideal_type.csv"에서 데이터 프레임 생성
ideal_type = pd.read_csv("https://raw.githubusercontent.com/imbiotech/skbtML/main/4-4-1.ideal_type.csv")
ideal_type.head()


talkativeness_level  interest_in_books  interest_in_traveling   
0                   30                 80                     40  \
1                   60                 50                     70   
2                   50                 40                     80   
3                   90                 50                     60   
4                   50                 70                     30   

   academic_performance  height  skin_condition  muscularity_level   
0                    40      90              90                 50  \
1                    50      60              60                 90   
2                    60      50              70                 80   
3                    30      40              20                 30   
4                    70      70              80                 60   

  attraction_label  
0           Type 1  
1           Type 2  
2           Type 2  
3           Type 3  
4           Type 1

In [ ]:
# 데이터와 결과를 분리
ideal_type_data = ideal_type.drop("attraction_label", axis=1)
ideal_type_target = ideal_type["attraction_label"]

# 데이터와 결과를 array로 변환
ideal_type_data_array = np.array(ideal_type_data)
ideal_type_target_array = np.array(ideal_type_target)

ideal_type_data_array, ideal_type_target_array

(array([[30, 80, 40, 40, 90, 90, 50],
        [60, 50, 70, 50, 60, 60, 90],
        [50, 40, 80, 60, 50, 70, 80],
        [90, 50, 60, 30, 40, 20, 30],
        [50, 70, 30, 70, 70, 80, 60],
        [70, 30, 60, 40, 40, 40, 30],
        [40, 90, 60, 60, 60, 80, 60],
        [30, 60, 90, 60, 40, 70, 70],
        [80, 40, 20, 80, 60, 40, 50],
        [50, 70, 70, 50, 70, 90, 50],
        [80, 50, 60, 40, 50, 40, 70],
        [30, 70, 30, 90, 70, 80, 60],
        [40, 60, 90, 60, 50, 70, 80],
        [80, 30, 50, 50, 80, 40, 60]], dtype=int64),
 array(['Type 1', 'Type 2', 'Type 2', 'Type 3', 'Type 1', 'Type 3',
        'Type 1', 'Type 2', 'Type 3', 'Type 1', 'Type 3', 'Type 1',
        'Type 2', 'Type 3'], dtype=object))

In [ ]:
# 데이터 정규화를 위해 StandardScaler 함수 불러오고 StandardScaler 생성
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler() 

# fit_transform 함수를 사용하여 데이터를 표준화
ideal_type_data_array = scaler.fit_transform(ideal_type_data_array)
ideal_type_data_array

array([[-1.26962211e+00,  1.34164079e+00, -8.46121804e-01,
        -9.87829161e-01,  2.06644812e+00,  1.29927838e+00,
        -5.91607978e-01],
       [ 2.11603685e-01, -3.65902033e-01,  5.75362827e-01,
        -3.59210604e-01,  4.80569331e-02, -9.99444907e-02,
         1.77482393e+00],
       [-2.82138246e-01, -9.35082972e-01,  1.04919104e+00,
         2.69407953e-01, -6.24740131e-01,  3.66463133e-01,
         1.18321596e+00],
       [ 1.69282948e+00, -3.65902033e-01,  1.01534617e-01,
        -1.61644772e+00, -1.29753719e+00, -1.96557498e+00,
        -1.77482393e+00],
       [-2.82138246e-01,  7.72459847e-01, -1.31995001e+00,
         8.98026510e-01,  7.20853997e-01,  8.32870756e-01,
        -3.05877772e-17],
       [ 7.05345616e-01, -1.50426391e+00,  1.01534617e-01,
        -9.87829161e-01, -1.29753719e+00, -1.03275974e+00,
        -1.77482393e+00],
       [-7.75880177e-01,  1.91082173e+00,  1.01534617e-01,
         2.69407953e-01,  4.80569331e-02,  8.32870756e-01,
        -3.0587777

In [ ]:
# KNN 분류 모델 생성 및 훈련
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=5) # KNN 분류 모델 생성, 이웃의 수는 5으로 설정
model.fit(ideal_type_data_array, ideal_type_target_array) # 모델 훈련

# 예측 결과 확인
ideal_type_pred = model.predict(ideal_type_data_array)
print(ideal_type_pred) # 모델이 예측한 결과

# confusion_matrix 함수를 사용하여 오차 행렬 출력
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(ideal_type_target_array, model.predict(ideal_type_data_array))) # 오차 행렬(혼돈 행렬) 출력, 혼돈 행렬의 숫자는 데이터가 대각선일수록 좋음
print(classification_report(ideal_type_target_array, ideal_type_pred)) # 정밀도, 재현율, F1 점수 출력

['Type 1' 'Type 2' 'Type 2' 'Type 3' 'Type 1' 'Type 3' 'Type 1' 'Type 2'
 'Type 3' 'Type 1' 'Type 3' 'Type 1' 'Type 2' 'Type 3']
[[5 0 0]
 [0 4 0]
 [0 0 5]]
              precision    recall  f1-score   support

      Type 1       1.00      1.00      1.00         5
      Type 2       1.00      1.00      1.00         4
      Type 3       1.00      1.00      1.00         5

    accuracy                           1.00        14
   macro avg       1.00      1.00      1.00        14
weighted avg       1.00      1.00      1.00        14

